/*
MYSQL E-COMMERCE DATA ANALYTICS PROJECT — QUESTIONS ONLY

Tables:
customers(customer_id, first_name, last_name, email, address, city, state_province)
orders(order_id, customer_id, order_date)
product_orders(order_id, product_id, quantity, unit_price)
products(product_id, product_name, product_type)

MySQL 8.0+.
Focus: JOINS, WINDOW FUNCTIONS, CTEs, SUBQUERIES.
Revenue = quantity * unit_price.
*/

/* Q1. Customer Revenue Analysis
Find every customer who has placed at least one order.
Show:
- customer_id
- customer name
- number of orders
- total quantity purchased
- total revenue
Sort by total revenue from highest to lowest. */

select c.customer_id,concat(c.first_name,' ' ,c.last_name) as customer_name, count(distinct o.order_id) as total_orders , 
sum(po.quantity) as total_quantity , sum(po.unit_price *po.quantity) as total_revenue from customers c
join orders o
on c.customer_id=o.customer_id
join product_orders po
on o.order_id=po.order_id 
group by c.customer_id,customer_name 
having count(o.order_id) >=1
order by total_revenue desc;


/* Q2. Product Performance
Find the total revenue and total quantity sold for every product.
Show:
- product_id
- product_name
- product_type
- total_quantity
- total_revenue
Include only products that have been ordered. */
select p.product_id,p.product_name,p.product_type,sum(po.quantity) as total_quantity , sum(po.unit_price*po.quantity) as total_revenue
from products p 
join product_orders po
on p.product_id=po.product_id
group by p.product_id,p.product_name,p.product_type;



/* Q3. Product-Type Revenue Analysis
Find total revenue generated by each product type.
Show:
- product_type
- number of distinct products sold
- total quantity sold
- total revenue */   

select p.product_type,count(distinct po.product_id) as distinct_product_sold ,
sum(po.quantity) as total_quantity_sold,
sum(po.unit_price*po.quantity) as total_revenue 
from products p
join product_orders po
on p.product_id=po.product_id
group by  p.product_type;

/* Q4. Customers With No Orders
Find customers who have never placed an order.
Show:
- customer_id
- customer name
- city
- state_province */
select c.customer_id,concat(c.first_name,' ' ,c.last_name) as customer_name,c.city,c.state_province from customers c
left join orders o
on c.customer_id=o.customer_id
where o.order_id is null;


/* Q5. Products Never Ordered
Find products that have never appeared in product_orders.
Show:
- product_id
- product_name
- product_type */
select p.product_id,p.product_name,p.product_type from products p
left join product_orders po
on p.product_id =po.product_id
WHERE po.order_id IS NULL;

/* Q6. Order-Level Revenue
For every order, calculate the total order value.
Also show:
- order_id
- order_date
- customer_id
- customer name
- total items
- order_value */

select o.order_id,
o.order_date,
c.customer_id,
concat(c.first_name,' ' ,c.last_name) as customer_name,
sum(po.quantity) as total_items,
sum(po.unit_price*po.quantity) as total_revenue from customers c
join orders o
on c.customer_id=o.customer_id
join product_orders po
on o.order_id=po.order_id
group by o.order_id,
o.order_date,
c.customer_id,
customer_name;


/* Q7. Rank Customers by Revenue
Calculate each customer's total revenue and rank customers
from highest to lowest revenue using DENSE_RANK().
Show:
- customer_id
- customer_name
- total_revenue
- revenue_rank */

select c.customer_id ,
concat(c.first_name,' ' ,c.last_name) as customer_name,
sum(po.unit_price*po.quantity) as total_revenue ,
dense_rank() over(order by sum(po.unit_price*po.quantity) desc) as rnk  from customers c
join orders o
on c.customer_id=o.customer_id
join product_orders po
on o.order_id=po.order_id
group by c.customer_id ,customer_name
;



/* Q8. Top 3 Products Within Each Product Type
Calculate revenue for every product and return the top 3
products within each product_type using ROW_NUMBER(). */
select *  from
(select p.product_id ,p.product_name,p.product_type , sum(po.unit_price*po.quantity) as total_revenue ,
Row_number() over(partition by p.product_type order by sum(po.unit_price*po.quantity)  desc) as rank_product from products p
join product_orders po
on p.product_id=po.product_id 
group by p.product_id ,p.product_name,p.product_type) as t 
where rank_product<=3;

/* Q9. Running Monthly Revenue
Calculate total revenue for each month and the cumulative
(running) revenue over time.
Show:
- month
- monthly_revenue
- cumulative_revenue */
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(po.quantity * po.unit_price) AS monthly_revenue
    FROM orders o
    JOIN product_orders po
        ON o.order_id = po.order_id
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT
    month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY month
    ) AS cumulative_revenue
FROM monthly_revenue
ORDER BY month;

/* Q10. Customer Order Sequence
For every order, show the customer's:
- order sequence number
- order_id
- order_date
- customer_id

The first order for a customer should have sequence number 1. */

select row_number() over(partition by c.customer_id  order by o.order_date asc)  order_sequence
,o.order_id,
o.order_date,
c.customer_id 
from customers c
join orders o 
on c.customer_id=o.customer_id ;

/* Q11. Days Between Customer Orders
Use LAG() to calculate the number of days between each
customer's current order and previous order. */
select * ,  DATEDIFF(order_date, previous_order_date) AS days_between_orders from
(select c.customer_id ,
o.order_id,
o.order_date,
lag(o.order_date) over(partition by customer_id ORDER BY o.order_date) as previous_order_date from customers c
join orders o
on c.customer_id=o.customer_id)as t; 

/* Q12. Order Contribution to Customer Revenue
For every order, calculate:
- order value
- customer's total revenue
- percentage of customer revenue contributed by that order
Use a window function to calculate the customer total. */
WITH cte AS (
    SELECT
        customer_id,
        order_id,
        order_value,
        SUM(order_value) OVER (
            PARTITION BY customer_id
        ) AS customer_total_revenue
    FROM (
        SELECT
            o.customer_id,
            o.order_id,
            SUM(po.quantity * po.unit_price) AS order_value
        FROM orders o
        JOIN product_orders po
            ON o.order_id = po.order_id
        GROUP BY o.customer_id, o.order_id
    ) AS t
)
SELECT
    customer_id,
    order_id,
    order_value,
    customer_total_revenue,
    (order_value / customer_total_revenue) * 100
        AS percentage_of_customer_revenue
FROM cte;


/* Q13. Highest-Value Order for Every Customer
Return only the highest-value order for each customer.
If two orders have the same value, use the earlier order. */
WITH cte AS (
    SELECT
        customer_id,
        order_id,
        order_date,
        order_value,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id
            ORDER BY order_value DESC,
                     order_date ASC,
                     order_id ASC
        ) AS rnk
    FROM (
        SELECT
            o.customer_id,
            o.order_id,
            o.order_date,
            SUM(po.quantity * po.unit_price) AS order_value
        FROM orders o
        JOIN product_orders po
            ON o.order_id = po.order_id
        GROUP BY
            o.customer_id,
            o.order_id,
            o.order_date
    ) AS t
)
SELECT
    customer_id,
    order_id,
    order_date,
    order_value
FROM cte
WHERE rnk = 1;


/* Q14. Monthly Revenue Growth
Calculate monthly revenue and compare each month with the
previous month using LAG().
Show:
- month
- monthly_revenue
- previous_month_revenue
- revenue_change
- growth_percentage */
WITH cte AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(po.quantity * po.unit_price) AS monthly_revenue
    FROM orders o
    JOIN product_orders po
        ON o.order_id = po.order_id
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
),
growth AS (
    SELECT
        month,
        monthly_revenue,
        LAG(monthly_revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM cte
)
SELECT
    month,
    monthly_revenue,
    previous_month_revenue,
    monthly_revenue - previous_month_revenue AS revenue_change,
    ((monthly_revenue - previous_month_revenue)
        / NULLIF(previous_month_revenue, 0)) * 100
        AS growth_percentage
FROM growth
ORDER BY month;

/* Q15. Customer Purchase Segmentation
Using a CTE, calculate each customer's:
- total orders
- total revenue

Then classify customers as:
- High Value: revenue >= 1000
- Medium Value: revenue >= 500 and < 1000
- Low Value: revenue < 500

Return customer_id, customer_name, orders, revenue, segment. */
 with cte as (
 select c.customer_id ,
 concat(c.first_name,' ',c.last_name) as customer_name,
 count(distinct o.order_id) as total_orders,
 sum(po.quantity*po.unit_price) as total_revenue from customers c
 join orders o
 on c.customer_id=o.customer_id
 join product_orders po
 on o.order_id=po.order_id
 group by c.customer_id, c.first_name,c.last_name
 )
 ,classify as ( select *,case when  total_revenue >= 1000 then'high value'
 when total_revenue >= 500 
                 AND total_revenue < 1000 THEN 'Medium Value'
 else 'low value'
 end as segment from cte)
 select customer_id,customer_name, total_orders as orders ,total_revenue as revenue ,segment from classify;



/* Q16. Product Type Performance
Using CTEs, calculate revenue for every product and then
summarize the results by product_type.
Show:
- product_type
- products_sold
- total_quantity
- total_revenue
- average_product_revenue */
with cte as
(select
p.product_type ,
p.product_id,
sum(po.quantity) as total_quantity,
sum(po.quantity*po.unit_price) as total_revenue from products p
join product_orders po
on p.product_id=po.product_id
group by  p.product_type ,p.product_id
)
select product_type , COUNT(product_id) AS products_sold, sum(total_quantity) as total_quantity , sum(total_revenue) as total_revenue, avg(total_revenue) as average_product_revenue from cte 
group by product_type ;

/* Q17. Top 5 Customers in Each Month
Using a CTE and ROW_NUMBER(), find the top 5 customers
by revenue in every month. */
WITH cte AS (
    SELECT
        o.customer_id,
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(po.quantity * po.unit_price) AS total_revenue
    FROM orders o
    JOIN product_orders po
        ON o.order_id = po.order_id
    GROUP BY
        o.customer_id,
        DATE_FORMAT(o.order_date, '%Y-%m')
),
ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY month
            ORDER BY total_revenue DESC
        ) AS rnk
    FROM cte
)
SELECT *
FROM ranked
WHERE rnk <= 5
ORDER BY month, rnk;


/* Q18. Customers With Increasing Order Activity
Find customers whose last order value is greater than their
first order value.

Return:
- customer_id
- first_order_value
- last_order_value
- increase_amount */
WITH order_values AS (
    SELECT 
        o.customer_id,
        o.order_id,
        o.order_date,
        SUM(po.quantity * po.unit_price) AS order_value
    FROM orders o
    JOIN product_orders po
        ON o.order_id = po.order_id
    GROUP BY 
        o.customer_id,
        o.order_id,
        o.order_date
),

ranked AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id 
            ORDER BY order_date ASC, order_id ASC
        ) AS first_order_rank,
        
        ROW_NUMBER() OVER (
            PARTITION BY customer_id 
            ORDER BY order_date DESC, order_id DESC
        ) AS last_order_rank
    FROM order_values
),

customer_orders AS (
    SELECT 
        customer_id,
        MAX(CASE 
            WHEN first_order_rank = 1 
            THEN order_value 
        END) AS first_order_value,
        
        MAX(CASE 
            WHEN last_order_rank = 1 
            THEN order_value 
        END) AS last_order_value
    FROM ranked
    GROUP BY customer_id
)

SELECT 
    customer_id,
    first_order_value,
    last_order_value,
    last_order_value - first_order_value AS increase_amount
FROM customer_orders
WHERE last_order_value > first_order_value;

/* Q19. Orders Above Monthly Average
Using CTEs, calculate each order's value and the average
order value for its month.
Return orders whose value is greater than their month's
average order value. */

with cte as(select o.order_id,
month(o.order_date) as months
,sum(po.quantity*po.unit_price)  as order_value
from orders o
join product_orders po
on o.order_id=po.order_id
group by  o.order_id,
month(o.order_date))
,avg_order_value as
(select months,avg(order_value) as avg_order_value_month
from cte group by months)
select  c.order_id ,c.order_value,av.avg_order_value_month from avg_order_value av
join cte c
on av.months=c.months
where c.order_value>av.avg_order_value_month;


/* Q20. Customer Retention / Repeat Purchase Analysis
Using CTEs, find customers who placed at least 2 orders.
Show:
- customer_id
- first_order_date
- last_order_date
- total_orders
- days_between_first_and_last_order */

with cte as (select customer_id 
,max(order_date) as last_order_date,
min(order_date ) as first_order_date ,
count(distinct order_id) as total_orders 
from orders 
group by customer_id 
having count(distinct order_id)>=2 )
select * , datediff(last_order_date,first_order_date) as days_between_first_and_last_order from cte ;
/* Q21. Customers Spending Above Average
Find customers whose total revenue is greater than the
average revenue of all customers who have placed orders.

Show:
- customer_id
- customer_name
- total_revenue */

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(po.quantity * po.unit_price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN product_orders po
    ON o.order_id = po.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
HAVING SUM(po.quantity * po.unit_price) >
(
    SELECT AVG(total_revenue)
    FROM (
        SELECT
            o.customer_id,
            SUM(po.quantity * po.unit_price) AS total_revenue
        FROM orders o
        JOIN product_orders po
            ON o.order_id = po.order_id
        GROUP BY o.customer_id
    ) AS t
);

/* Q22. Products Above Average Revenue
Find products whose total revenue is greater than the
average revenue across all products that have been ordered. */

select p.product_id,
p.product_name,
sum(po.quantity * po.unit_price) as total_revenue
from products p
join product_orders po
on p.product_id=po.product_id
group by p.product_id,
p.product_name
having sum(po.quantity * po.unit_price) > (select avg(total_revenue1) from (select p.product_id,
p.product_name,
sum(po.quantity * po.unit_price) as total_revenue1
from products p
join product_orders po
on p.product_id=po.product_id
group by p.product_id,
p.product_name) as t);

/* Q23. Orders Above the Customer's Average Order Value
Find orders whose value is greater than the average order
value of the same customer.

Show:
- order_id
- customer_id
- order_date
- order_value
- customer_average_order_value */
WITH order_values AS (
    SELECT 
        o.order_id,
        o.customer_id,
        o.order_date,
        SUM(po.quantity * po.unit_price) AS order_value
    FROM orders o
    JOIN product_orders po
        ON o.order_id = po.order_id
    GROUP BY 
        o.order_id,
        o.customer_id,
        o.order_date
),

cte AS (
    SELECT *,
        AVG(order_value) OVER (
            PARTITION BY customer_id
        ) AS customer_average_order_value
    FROM order_values
)

SELECT *
FROM cte
WHERE order_value > customer_average_order_value;

/* Q24. Customers With At Least 3 Orders
Find customers who have placed at least 3 orders.
Return customer details and their order count.
Use a subquery to identify qualifying customers. */

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.city,
    c.state_province,
    t.total_orders
FROM customers c
JOIN (
    SELECT 
        customer_id,
        COUNT(order_id) AS total_orders
    FROM orders
    GROUP BY customer_id
    HAVING COUNT(order_id) >= 3
) AS t
    ON c.customer_id = t.customer_id;




/* Q25. Customers Who Bought a Specific Product Type
Find customers who have purchased at least one product from
the 'oven' product type.
Show each customer only once. */
SELECT DISTINCT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN product_orders po
    ON o.order_id = po.order_id
JOIN products p
    ON po.product_id = p.product_id
WHERE p.product_type = 'oven';


/* Q26. Second-Highest Revenue Product
Find the product with the second-highest total revenue.

Use a subquery rather than LIMIT/OFFSET. */

WITH cte AS (
    SELECT
        p.product_id,
        p.product_name,
        SUM(po.quantity * po.unit_price) AS total_revenue
    FROM products p
    JOIN product_orders po
        ON p.product_id = po.product_id
    GROUP BY
        p.product_id,
        p.product_name
)
SELECT
    product_id,
    product_name,
    total_revenue AS second_highest_revenue
FROM cte
WHERE total_revenue = (
    SELECT MAX(total_revenue)
    FROM cte
    WHERE total_revenue < (
        SELECT MAX(total_revenue)
        FROM cte
    )
);
 
 
